name: Deployment

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: ''
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Checking Files
        run: |
          ls -la
      - name: Installing Packages
        run: npm install
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
        name: Setup Git
      - name: Build, Push & Deploy
        run: |
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
